export const animeList = [
	{
		id: 1,
		title: "Атака Титанов",
		image: "/Attack.on.Titan.jpg",
		links: {
			"Сезон 1 Серия 1": "https://yadi.sk/i/2XnOsl13SGHWug",
			"Сезон 1 Серия 2": "https://yadi.sk/d/eNh47avKiSwRyQ",
			"Сезон 1 Серия 3": "https://yadi.sk/i/ZttSK_GJeKEvlA",
			"Сезон 1 Серия 4": "https://yadi.sk/i/YohgVabQmeDydQ",
			"Сезон 1 Серия 5": "https://yadi.sk/i/MQ0RiFO6fyvEZg",
			"Сезон 1 Серия 6": "https://yadi.sk/d/5TUZfwtMYWyK3g",
			"Сезон 1 Серия 7": "https://yadi.sk/d/q7m9FY3unQtgIA",
			"Сезон 1 Серия 8": "https://yadi.sk/d/QWya-kaKlIV24w",
			"Сезон 1 Серия 9": "https://yadi.sk/i/8o_UXBIj4sCrsQ",
			"Сезон 1 Серия 10": "https://yadi.sk/i/IhKuBQyoP47pZQ",
			"Сезон 1 Серия 11": "https://yadi.sk/d/vGCVed_eT0mYZg",
			"Сезон 1 Серия 12": "https://yadi.sk/d/0FLOSMhBE5OB2Q",
			"Сезон 1 Серия 13": "https://yadi.sk/d/YoWlfNLQYaahmQ",
			"Сезон 1 Серия 14": "https://yadi.sk/i/MbQXpPFyIkJiIg",
			"Сезон 1 Серия 15": "https://yadi.sk/i/mw41xzWpNcoZ8A",
			"Сезон 1 Серия 16": "https://yadi.sk/i/m7JjQMuBFOsmMw",
			"Сезон 1 Серия 17": "https://yadi.sk/d/Ef3ZwZKVXkaIFA",
			"Сезон 1 Серия 18": "https://yadi.sk/i/fhca7Q1U6k5pxg",
			"Сезон 1 Серия 19": "https://yadi.sk/i/9t02IqE3cbPTbQ",
			"Сезон 1 Серия 20": "https://yadi.sk/i/u-UuRm7_vLqukQ",
			"Сезон 1 Серия 21": "https://yadi.sk/i/c7xNJOECi21RqQ",
			"Сезон 1 Серия 22": "https://yadi.sk/d/bIQL64wi9PfHqg",
			"Сезон 1 Серия 23": "https://yadi.sk/i/Wg5y_b1bQHCEdw",
			"Сезон 1 Серия 24": "https://yadi.sk/i/1m9SNglnxZU4nw",
			"Сезон 1 Серия 25": "https://yadi.sk/d/bxBwkIbTpFn0Mg",
			"Сезон 2 Серия 1": "https://yadi.sk/d/6r2Fv395jjoztQ",
			"Сезон 2 Серия 2": "https://yadi.sk/d/EcjCr9WX4j7cGg",
			"Сезон 2 Серия 3": "https://yadi.sk/d/fD6Assl-zcrH5A",
			"Сезон 2 Серия 4": "https://yadi.sk/d/etjRQWvx8VDSOA",
			"Сезон 2 Серия 5": "https://yadi.sk/d/zSlP5ZHQ9zv6EQ",
			"Сезон 2 Серия 6": "https://yadi.sk/d/_A2FZ6JQmdWRTg",
			"Сезон 2 Серия 7": "https://yadi.sk/d/5IdEx7AEEnjfEw",
			"Сезон 2 Серия 8": "https://yadi.sk/d/CBIGCepiBLrY3g",
			"Сезон 2 Серия 9": "https://yadi.sk/d/jkGSvJL8h2B8IA",
			"Сезон 2 Серия 10": "https://yadi.sk/d/SWvGOLAdz-gGAQ",
			"Сезон 2 Серия 11": "https://yadi.sk/d/7MTVuZL_YjB8tQ",
			"Сезон 2 Серия 12": "https://yadi.sk/d/v8vRL6rxo_4nqQ",
			"Сезон 3 Серия 1": "https://yadi.sk/d/2Yk0_gWW9C8F1A",
			"Сезон 3 Серия 2": "https://yadi.sk/d/HWoRZUIXGUQImg",
			"Сезон 3 Серия 3": "https://yadi.sk/i/1qxyd1_9dh5xPg",
			"Сезон 3 Серия 4": "https://yadi.sk/d/dX0EOPOPZQ1Hog",
			"Сезон 3 Серия 5": "https://yadi.sk/i/thYA0LzdJ5Euug",
			"Сезон 3 Серия 6": "https://yadi.sk/i/YASUp1P-tnwvYw",
			"Сезон 3 Серия 7": "https://yadi.sk/d/N0nd57PIvP9f6w",
			"Сезон 3 Серия 8": "https://yadi.sk/i/k3hNZrcGGCjWtw",
			"Сезон 3 Серия 9": "https://yadi.sk/i/okvc_NjdckR0Vg",
			"Сезон 3 Серия 10": "https://yadi.sk/i/1cRkyXAfZUKAxA",
			"Сезон 3 Серия 11": "https://yadi.sk/i/M09pGOIAI6EYBw",
			"Сезон 3 Серия 12": "https://yadi.sk/i/dUrl4zxra6ucUQ",
			"Сезон 3 Серия 13": "https://yadi.sk/i/jy-Fl2QFSTsyrw",
			"Сезон 3 Серия 14": "https://yadi.sk/i/R7YMlxhKJicc9A",
			"Сезон 3 Серия 15": "https://yadi.sk/i/Ltv-wmi39HgtwA",
			"Сезон 3 Серия 16": "https://yadi.sk/i/WtPC_y_r-y9diA",
			"Сезон 3 Серия 17": "https://yadi.sk/d/Xvx1cPyHXqeyrQ",
			"Сезон 3 Серия 18": "https://yadi.sk/i/HF04-SXQTanXTg",
			"Сезон 3 Серия 19": "https://yadi.sk/d/Co0xwzjNWs8DHw",
			"Сезон 3 Серия 21": "https://yadi.sk/i/5j4nf4GeNF_chA",
			"Сезон 3 Серия 22": "https://yadi.sk/d/m4ykSk4hTtOmfQ",
			"Сезон 4 Серия 1": "https://yadi.sk/d/DgXE-ENCwho_wQ",
			"Сезон 4 Серия 2": "https://yadi.sk/d/mHHbSe-wD-BNGg",
			"Сезон 4 Серия 3": "https://yadi.sk/i/ZgTWbsZ3SWi9Sw",
			"Сезон 4 Серия 4": "https://yadi.sk/i/_domKQXwKBZbJA",
			"Сезон 4 Серия 5": "https://yadi.sk/i/agY8gDGvUNyvKw",
			"Сезон 4 Серия 6": "https://yadi.sk/i/llQpoMwGC2ieqg",
			"Сезон 4 Серия 7": "https://yadi.sk/i/Oqy6lvZOVAubVQ",
			"Сезон 4 Серия 8": "https://yadi.sk/i/xelNjUzeTfsQyw",
			"Сезон 4 Серия 9": "https://yadi.sk/d/1onIJM9mCgBmpQ",
			"Сезон 4 Серия 10": "https://yadi.sk/i/Kj7Y-wKeNlDgzg",
			"Сезон 4 Серия 11": "https://yadi.sk/d/k9xAuxM9JHT3FQ",
			"Сезон 4 Серия 12": "https://yadi.sk/i/raOe0yfsJcAmPA",
			"Сезон 4 Серия 13": "https://yadi.sk/d/dz2jGUNi1x5fiQ",
			"Сезон 4 Серия 14": "https://yadi.sk/d/tXBxcwGQzle7iw",
			"Сезон 4 Серия 15": "https://yadi.sk/d/fPBQNKwlLtQppA",
			"Сезон 4 Серия 16": "https://yadi.sk/d/HOmPVI6OXi8qrw",
			"Сезон 4 Серия 17": "https://yadi.sk/i/RqND8_qFCfFFxg",
			"Сезон 4 Серия 18": "https://yadi.sk/i/z4SElv-vNAxoAQ",
			"Сезон 4 Серия 19": "https://yadi.sk/d/Wqbb2IqJpZcfgQ",
			"Сезон 4 Серия 20": "https://yadi.sk/d/O8F760GSkKqNPQ",
			"Сезон 4 Серия 21": "https://yadi.sk/i/uRnryRC8_nMUvQ",
			"Сезон 4 Серия 22": "https://yadi.sk/i/UcF5mM3a-XHYIg",
			"Сезон 4 Серия 23": "https://yadi.sk/d/JzMvlb481xOcjg",
			"Сезон 4 Серия 24": "https://yadi.sk/d/mYZa-c-cjCtiLg",
			"Сезон 4 Серия 25": "https://yadi.sk/i/JrGutwzKh8UbNA",
			"Сезон 4 Серия 26": "https://yadi.sk/i/jhYHPPkBxeW6nA",
			"Сезон 4 Серия 27": "https://yadi.sk/d/xsWjDUWNm0zeHg",
			"Сезон 4 Серия 28": "https://yadi.sk/d/HRtfaua2OlwEWw",
			"Сезон 4 Серия 29": "https://yadi.sk/d/buBereC9FdGZJg",
			"Сезон 4 Серия 30": "https://yadi.sk/d/uJHoVNCnGqbZ9A",
		},
	},
	{
		id: 2,
		title: "Тетрадь смерти",
		image: "/Death.Note.jpg",
		links: {},
	},
	{
		id: 3,
		title: "Адский рай",
		image: "/Hells.paradise.jpg",
		links: {
			"Сезон 1 Серия 1": "https://yadi.sk/d/kepLAVZZHtSAKQ",
			"Сезон 1 Серия 2": "https://yadi.sk/d/mBR7T_9W1qi5hw",
			"Сезон 1 Серия 3": "https://yadi.sk/d/D4evc7uzyJbBAw",
			"Сезон 1 Серия 4": "https://yadi.sk/d/VaRXQAcLjAlEGA",
			"Сезон 1 Серия 5": "https://yadi.sk/d/lC0ZLSx0g0Ndgw",
			"Сезон 1 Серия 6": "https://yadi.sk/d/Wqtw7sqNawN8Hw",
			"Сезон 1 Серия 7": "https://yadi.sk/d/FGSY3kN4QIcsUg",
			"Сезон 1 Серия 8": "https://yadi.sk/d/kCBgf0AyUuaOOg",
			"Сезон 1 Серия 9": "https://yadi.sk/d/4ZN18aGKdSivXw",
			"Сезон 1 Серия 10": "https://yadi.sk/d/84UGxrz2fz2Z1g",
			"Сезон 1 Серия 11": "https://yadi.sk/d/IUm3827WzYPJyg",
			"Сезон 1 Серия 12": "https://yadi.sk/d/nDunmZtpFW3ung",
			"Сезон 1 Серия 13": "https://yadi.sk/d/dWfSNK_xGnmpag",
		},
	},
	{
		id: 4,
		title: "Кабанэри железной крепости",
		image: "/Kabaneri.of.the.Iron.Fortress.jpg",
		links: {
			"Серия 1": "https://yadi.sk/d/I5xG_uigg-xuaA",
			"Серия 2": "https://yadi.sk/d/WJUTlGrrUnx7Rg",
			"Серия 3": "https://yadi.sk/d/nn6J3aUY8IwyKg",
			"Серия 4": "https://yadi.sk/d/4GMNMr_vfcKlmA",
			"Серия 5": "https://yadi.sk/d/dLVp2XfUGXE6WQ",
			"Серия 6": "https://yadi.sk/d/T-2y1l_Cjdyv5g",
			"Серия 7": "https://yadi.sk/d/IQzljg_K6lH4rg",
			"Серия 8": "https://yadi.sk/d/cxOrmE6pD9m8qA",
			"Серия 9": "https://yadi.sk/d/9XZ9ELJIdBGxyw",
			"Серия 10": "https://yadi.sk/d/kG8i4NoR227ENA",
			"Серия 11": "https://yadi.sk/d/5dhogdUj1JTfYw",
			"Серия 12": "https://yadi.sk/d/sJgesPGq9t916Q",
		},
	},
	{
		id: 5,
		title: "Провожающая в последний путь Фрирен",
		image: "/Sousou.no.Frieren.jpg",
		links: {
			"Сезон 1 Серия 1": "https://yadi.sk/d/rET6rq2XfXffJA",
			"Сезон 1 Серия 2": "https://yadi.sk/d/rXqWcHufSObBDg",
			"Сезон 1 Серия 3": "https://yadi.sk/d/j44d4N9HdwC0_A",
			"Сезон 1 Серия 4": "https://yadi.sk/d/-Fi1FMpsLkZC_Q",
			"Сезон 1 Серия 5": "https://yadi.sk/d/-bgMigBnuVZg7w",
			"Сезон 1 Серия 6": "https://yadi.sk/d/SL_II2tKoTWzRA",
			"Сезон 1 Серия 7": "https://yadi.sk/d/Pssk-3FZ76N6hA",
			"Сезон 1 Серия 8": "https://yadi.sk/d/No4dentb5JS7pQ",
			"Сезон 1 Серия 9": "https://yadi.sk/d/ZIxuQMYMBaNIqw",
			"Сезон 1 Серия 10": "https://yadi.sk/d/WhVsq5talQbK6g",
			"Сезон 1 Серия 11": "https://yadi.sk/d/3C3G5_KPZsyDWw",
			"Сезон 1 Серия 12": "https://yadi.sk/d/AkWf1q73FTQiIw",
			"Сезон 1 Серия 13": "https://yadi.sk/d/11G5pve1tMjV-Q",
			"Сезон 1 Серия 14": "https://yadi.sk/d/KwlDq0HCt5_WyA",
			"Сезон 1 Серия 15": "https://yadi.sk/d/ucpcFLk-EujCoA",
			"Сезон 1 Серия 16": "https://yadi.sk/d/Pbw9JaF4fMHGRA",
			"Сезон 1 Серия 17": "https://yadi.sk/d/2bW2UCLwAr_YpQ",
			"Сезон 1 Серия 18": "https://yadi.sk/d/LPF8MuFTBw8bKA",
			"Сезон 1 Серия 19": "https://yadi.sk/d/7yZcUjRO3zbPeQ",
			"Сезон 1 Серия 20": "https://yadi.sk/d/Q3Cm6NzSfl06pg",
			"Сезон 1 Серия 21": "https://yadi.sk/d/b6qaSayr34j8kQ",
			"Сезон 1 Серия 22": "https://yadi.sk/d/LDM7LnowCeCXjw",
			"Сезон 1 Серия 23": "https://yadi.sk/d/o16JdkFJcqVkCA",
			"Сезон 1 Серия 24": "https://yadi.sk/d/BFgx0-JDrQSY0g",
			"Сезон 1 Серия 25": "https://yadi.sk/d/nqcp0NeyRwp4NQ",
			"Сезон 1 Серия 26": "https://yadi.sk/d/WY7mPr-xjf2hAA",
			"Сезон 1 Серия 27": "https://yadi.sk/d/LiEcYJMUuwEvyw",
			"Сезон 1 Серия 28": "https://yadi.sk/d/5pvHYA8b9LJ6ZQ",
		},
	},
];

export const mangaList = [
	{
		id: 1,
		title: "Атака Титанов",
		links: {
			"Том 1 Глава 1 Охота на Титана": "https://yadi.sk/d/6rBXlPA_KK-t3A",
			"Том 1 Глава 2 Этот день": "https://yadi.sk/d/WtU893-1R8tJYg",
			"Том 1 Глава 3 Ночь перед распределением":
				"https://yadi.sk/d/TZ4yrmfNO3YznQ",
			"Том 1 Глава 4 Столкновение": "https://yadi.sk/d/ZlVFsOyYwstW3w",
			"Том 2 Глава 5 Луч надежды в море отчаяния":
				"https://yadi.sk/d/z3l-7ajPfMNHPQ",
			"Том 2 Глава 6 Большой мир глазами маленькой девочки":
				"https://yadi.sk/d/7GLLUjs_Xy38yw",
			"Том 2 Глава 7 Короткое лезвие": "https://yadi.sk/d/NaNauaR0lfoPvg",
			"Том 2 Глава 8 Рёв": "https://yadi.sk/d/Ea1C6b23VjusiA",
			"Том 2 Глава 9 Слышу биение сердца его":
				"https://yadi.sk/d/C2jmadOYt-Us6g",
			"Том 3 Глава 10 Что случилось с левой рукой":
				"https://yadi.sk/d/uVZoSFBDn-Sbdg",
			"Том 3 Глава 11 Ответ": "https://yadi.sk/d/wfnsHv_7-8Pt8Q",
			"Том 3 Глава 12 Идол": "https://yadi.sk/d/p1DvbOyWyv2v5Q",
			"Том 3 Глава 13 Рана": "https://yadi.sk/d/PuCIMBknvtdXDA",
			"Том 4 Глава 14 Сокровенное желание": "https://yadi.sk/d/6wnqU-rCEzKGIQ",
			"Том 4 Глава 15 Один за другим": "https://yadi.sk/d/gjcvuacBDpEDOA",
			"Том 4 Глава 16 Потребность": "https://yadi.sk/d/WFEwxGOPOvesZg",
			"Том 4 Глава 17 Иллюзия силы": "https://yadi.sk/d/TuWhkbwEgRLZLA",
			"Том 4 Глава 18 Что дальше": "https://yadi.sk/d/0oJS8vXQjMTqxQ",
			"Том 5 Глава 19 Новый взгляд": "https://yadi.sk/d/x1jkZxRGZbnPSw",
			"Том 5 Глава 20 Отряд особого назначения":
				"https://yadi.sk/d/ixxH_XbjTAY3sw",
			"Том 5 Глава 21 И открылись врата": "https://yadi.sk/d/9Uc8Avcoye_qnQ",
			"Том 5 Глава 22 Засечь врага на подходе":
				"https://yadi.sk/d/v_UjWss7789xoA",
			"Том 6 Глава 23 Женская особь": "https://yadi.sk/d/gxfyEVvpO2nBNQ",
			"Том 6 Глава 24 Лес гигантских деревьев":
				"https://yadi.sk/d/5cdgUOwSOouGCg",
			"Том 6 Глава 25 Укус": "https://yadi.sk/d/ysJwRs94GGGGsQ",
			"Том 6 Глава 26 Верное решение": "https://yadi.sk/d/6VFk1RHLD1-vOA",
			"Том 7 Глава 27 Ирвин Смит": "https://yadi.sk/d/G3P_RHfNF94uFg",
			"Том 7 Глава 28 Выбор и его последствия":
				"https://yadi.sk/d/BRSCDr8VhMPRKQ",
			"Том 7 Глава 29 Схватка": "https://yadi.sk/d/c1uhdLwAOBi-XQ",
			"Том 7 Глава 30 Поверженные": "https://yadi.sk/d/_RnkmUaTLBKeGQ",
			"Том 8 Глава 31 Улыбка": "https://yadi.sk/d/7WUOj4ZJb79Lsg",
			"Том 8 Глава 32 Без доказательств": "https://yadi.sk/d/qa0iE1djZZBsxQ",
			"Том 8 Глава 33 Сокрытое за стеной": "https://yadi.sk/d/J0xUYp7fs01M1w",
			"Том 8 Глава 34 Танец воинов": "https://yadi.sk/d/rAGWB3Gnh_reDg",
			"Том 9 Глава 35 Горящий взгляд": "https://yadi.sk/d/K373UsJATeUHhQ",
			"Том 9 Глава 36 Я дома": "https://yadi.sk/d/S9or3178qxSQCQ",
			"Том 9 Глава 37 На юго-запад": "https://yadi.sk/d/wclDCRK1Wn0dyQ",
			"Том 9 Глава 38 Замок Утгард": "https://yadi.sk/d/PGSJITZuybMJFg",
			"Том 10 Глава 39 Солдат": "https://yadi.sk/d/n5u3MfaCnPBvhQ",
			"Том 10 Глава 40 Имир": "https://yadi.sk/d/ltJmN7m-kX5ooQ",
			"Том 10 Глава 41 Хистория": "https://yadi.sk/d/jMCk505c5T_KQw",
			"Том 10 Глава 42 Воин": "https://yadi.sk/d/i78R8_8f0JkiMg",
			"Том 11 Глава 43 Бронированный титан": "https://yadi.sk/d/ixA4OQ6IgFwzZg",
			"Том 11 Глава 44 Удар, бросок, захват":
				"https://yadi.sk/d/_VXhR9KpmMntLg",
			"Том 11 Глава 45 В погоню": "https://yadi.sk/d/2JYCRpAIam4Bog",
			"Том 11 Глава 46 Открытие": "https://yadi.sk/d/qJfT6s52HnH5YA",
			"Том 12 Глава 47 Дети": "https://yadi.sk/d/APFzJEyOpC1q-g",
			"Том 12 Глава 48 Хоть кто-нибудь": "https://yadi.sk/d/4ZcSQ77iW_VDFg",
			"Том 12 Глава 49 В атаку": "https://yadi.sk/d/KrYhXVgRIu1dNw",
			"Том 12 Глава 50 Крик": "https://yadi.sk/d/ErfvPjiXhCDwcQ",
			"Том 12 Глава 51 Экстра": "https://yadi.sk/d/xpX5SXChyvm19w",
			"Том 12 Глава 52 Экстра Прототип": "https://yadi.sk/d/YuS52b43vXmcbg",
			"Том 13 Глава 51 Отряд Райвеля": "https://yadi.sk/d/GxvC9mSotASGow",
			"Том 13 Глава 52 Криста Ленц": "https://yadi.sk/d/y9rAgnpJZUYR6w",
			"Том 13 Глава 53 Глупцы, что верят": "https://yadi.sk/d/UwX_veiOtlrY6w",
			"Том 13 Глава 54 И да начнется битва": "https://yadi.sk/d/1bdpbi9agsdbow",
			"Том 14 Глава 55 Боль": "https://yadi.sk/d/FfwD8YYvmDhwKg",
			"Том 14 Глава 56 Роли": "https://yadi.sk/d/R1iqVtcYWVsbgg",
			"Том 14 Глава 57 Кенни жнец": "https://yadi.sk/d/WmIiSbGusERW7g",
			"Том 14 Глава 58 Под обстрелом": "https://yadi.sk/d/muuCJGkgKzSiPQ",
			"Том 15 Глава 59 Душа монстра": "https://yadi.sk/d/X4FSD3Eh9E3Aug",
			"Том 15 Глава 60 Точка кипения": "https://yadi.sk/d/p6vXqoR2fsREuw",
			"Том 15 Глава 61 Финал": "https://yadi.sk/d/UOUI8M4DSOXJ4g",
			"Том 15 Глава 62 Грех": "https://yadi.sk/d/dl2Otv-FdkHu9g",
			"Том 16 Глава 63 Цепи": "https://yadi.sk/d/tSn4Ean7s980xw",
			"Том 16 Глава 64 Приветственная вечеринка":
				"https://yadi.sk/d/gBBtEGpcoLWwnQ",
			"Том 16 Глава 65 Мечты и проклятья": "https://yadi.sk/d/SuFVoLwth_Ka6Q",
			"Том 16 Глава 66 Желание": "https://yadi.sk/d/0-VEW3NZFFxs4g",
			"Том 17 Глава 67 Округ Орвуд, внешняя стена":
				"https://yadi.sk/d/m6Y6Vd8t86qiEA",
			"Том 17 Глава 68 Повелитель стен": "https://yadi.sk/d/a8GXPNqRT6E6ow",
			"Том 17 Глава 69 Друзья": "https://yadi.sk/d/QYNo7P1oz-PfNw",
			"Том 17 Глава 70 Мечты о прошлом": "https://yadi.sk/d/5eDgVblE7ojbcQ",
			"Том 17 Глава 71 Наблюдатель": "https://yadi.sk/d/-8USXvj_jwvAUQ",
			"Том 17 Глава 72 Ночь контратаки": "https://yadi.sk/d/oYaOxUY0nGRWvA",
			"Том 18 Глава 73 Город, где все началось":
				"https://yadi.sk/d/Qd4ML8PpCIm5SA",
			"Том 18 Глава 74 Залог успеха": "https://yadi.sk/d/TDy__O7Mjvxv7w",
			"Том 19 Глава 75 По разные стороны баррикад":
				"https://yadi.sk/d/CBFiyP83RwKUhA",
			"Том 19 Глава 76 Громовое копье": "https://yadi.sk/d/NOFz3A3e3bO4BA",
			"Том 19 Глава 77 Мир их глазами": "https://yadi.sk/d/iHlZPiSirlgaYQ",
			"Том 19 Глава 78 Сошествие на землю": "https://yadi.sk/d/REWxUjYkvu_RKA",
			"Том 20 Глава 79 Великолепная игра": "https://yadi.sk/d/epLUf_QV7JG_7w",
			"Том 20 Глава 80 Безымянные солдаты": "https://yadi.sk/d/zvFYHvoC5yomYw",
			"Том 20 Глава 81 Клятва": "https://yadi.sk/d/vql4Lb_JPQwCPQ",
			"Том 20 Глава 82 Герой": "https://yadi.sk/d/fmRSuGUsD7dF8A",
			"Том 21 Глава 83 Решимость": "https://yadi.sk/d/kummMnKISE26Qg",
			"Том 21 Глава 84 Белая ночь": "https://yadi.sk/d/2MwGUvlqERMQJg",
			"Том 21 Глава 85 Подвал": "https://yadi.sk/d/5EwtA93Yn0flbw",
			"Том 21 Глава 86": "https://yadi.sk/d/9J_EhbGlE1LKGg",
			"Том 21 Глава 87 Граница": "https://yadi.sk/d/4_Ly2KTdFMQiMA",
			"Том 22 Глава 88 Атака титанов": "https://yadi.sk/d/OB7jXJ0_r7cZ6A",
			"Том 22 Глава 89": "https://yadi.sk/d/zdIVFOniw6w1jw",
			"Том 22 Глава 90": "https://yadi.sk/d/IS0I7tMTISU8JA",
			"Том 23 Глава 91 По ту сторону океана":
				"https://yadi.sk/d/A8tqf3AotepfOA",
			"Том 23 Глава 92 Солдаты Марли": "https://yadi.sk/d/Xp97kzDMhg_3KA",
			"Том 23 Глава 93 Поезд в темной ночи": "https://yadi.sk/d/9O_2cWyjxqPJPg",
			"Том 23 Глава 95 Лжец": "https://yadi.sk/d/Q1vaBrypYxVe5A",
			"Том 24 Глава 100 Объявление войны": "https://yadi.sk/d/RE2jnYkRhjtywQ",
			"Том 24 Глава 96 Врата надежды": "https://yadi.sk/d/qyAZnTYaOnYPnw",
			"Том 24 Глава 97 Правда": "https://yadi.sk/d/J_c8Z3_cPGhqmg",
			"Том 24 Глава 98 Рад за тебя": "https://yadi.sk/d/X0fpPJ4WSpH6Iw",
			"Том 24 Глава 99 Тень вины": "https://yadi.sk/d/Mt_NYnUhZ-0wCQ",
			"Том 25 Глава 101 Молот войны": "https://yadi.sk/d/GvbtjMqpJlUWxw",
			"Том 25 Глава 102 Слишком поздно": "https://yadi.sk/d/GbJA5czNUaXvVQ",
			"Том 26 Глава 103": "https://yadi.sk/d/6f8Mq1TUUOO1yg",
			"Том 26 Глава 104 Победитель": "https://yadi.sk/d/sWEPwqQ6K37Zvw",
			"Том 26 Глава 105 Контратака Габи": "https://yadi.sk/d/emaZy3LmjRVb5w",
			"Том 26 Глава 106 Добровольцы": "https://yadi.sk/d/CTnLrcjw2CqsUQ",
			"Том 26 Глава 107 Посетитель": "https://yadi.sk/d/Ww1Y4HYcL4HMJA",
			"Том 27 Глава 108 Звонкое доказательство":
				"https://yadi.sk/d/tEnQ28hrYYRv9A",
			"Том 27 Глава 109 Гид": "https://yadi.sk/d/6CmQl45CjJ4HFw",
			"Том 27 Глава 110 Лжец": "https://yadi.sk/d/hMn35HrpZ299EQ",
			"Том 28 Глава 111 Дети в лесу": "https://yadi.sk/d/Nz5ZO7XS8Z5gGw",
			"Том 28 Глава 112 Невежество": "https://yadi.sk/d/_RkDHV-Y2_i8KQ",
			"Том 28 Глава 113 Жестокость": "https://yadi.sk/d/pU2Jk_1N1iGkbQ",
			"Том 28 Глава 114 Единственное спасение":
				"https://yadi.sk/d/b5DSLuX28tHz4Q",
			"Том 29 Глава 115 Поддержка": "https://yadi.sk/d/kJ_OCYyYx13FNg",
			"Том 29 Глава 116 Небеса и земля": "https://yadi.sk/d/gPSB46ITRFHzUw",
			"Том 29 Глава 117 Убеждение": "https://yadi.sk/d/cUM7kyh3Q8db1g",
			"Том 29 Глава 118 Грязная игра": "https://yadi.sk/d/q4ZYrMQslqBluw",
			"Том 29 Глава 119 Старшие братья и младшие братья":
				"https://yadi.sk/d/vb4kQj7cq8J6wg",
			"Том 30 Глава 120 Мгновение": "https://yadi.sk/d/reOO7cOzZUesJQ",
			"Том 30 Глава 121 Воспоминания о будущем":
				"https://yadi.sk/d/Abs7dbrX5ACyXA",
			"Том 30 Глава 122 На 2000 лет раньше тебя":
				"https://yadi.sk/d/HdENRXqUYFD3YQ",
			"Том 31 Глава 123 Демоны с острова": "https://yadi.sk/d/8VXjdQ4CRivLGQ",
			"Том 31 Глава 124 Рассеивание": "https://yadi.sk/d/DQ4U9sEHaUbOfA",
			"Том 31 Глава 125 Закат": "https://yadi.sk/d/sq8IjWH1kzEbIA",
			"Том 31 Глава 126 Честь": "https://yadi.sk/d/xWnBZebXLigNnQ",
			"Том 32 Глава 127 Ночь конца": "https://yadi.sk/d/7vLYr-gb7zHhKw",
			"Том 32 Глава 128 Предатель": "https://yadi.sk/d/7UC98DzAP0YZYg",
			"Том 32 Глава 129 Ностальгия": "https://yadi.sk/d/Urb6l73hMpjh1Q",
			"Том 33 Глава 130 Рассвет человечества":
				"https://yadi.sk/d/hJxoKo9AghZUEw",
			"Том 33 Глава 131 Дрожь земли": "https://yadi.sk/d/31B8Os44mf4q_w",
			"Том 33 Глава 132 Крылья Свободы": "https://yadi.sk/d/SfmYIP92hLaW_A",
			"Том 33 Глава 133 Грешники": "https://yadi.sk/d/ciOM9qFPavVDLA",
			"Том 33 Глава 134 В глубинах отчаяния":
				"https://yadi.sk/d/FDx8ODF5SOYSTg",
			"Том 34 Глава 135 Бой между небом и землёй":
				"https://yadi.sk/d/nHgtBjcLZ4zeSA",
			"Том 34 Глава 136 Посвятите свои сердца":
				"https://yadi.sk/d/1QRl9rbzA05SMQ",
			"Том 34 Глава 137 Титаны": "https://yadi.sk/d/HCxHwkpQ4nMg5w",
			"Том 34 Глава 138 Длинный Сон": "https://yadi.sk/d/exU24njgr-ADhw",
			"Том 34 Глава 139": "https://yadi.sk/d/I2QUe60Vl9-qNw",
		},
	},
	{
		id: 2,
		title: "Тетрадь смерти",
		links: {
			"Том 1 Глава 1": "https://yadi.sk/d/UDWqrtgd4JYwSQ",
			"Том 1 Глава 2": "https://yadi.sk/d/Gox7-BZ59O5T2g",
			"Том 1 Глава 3": "https://yadi.sk/d/9CFRCtaHtiu1pw",
			"Том 1 Глава 4": "https://yadi.sk/d/RRxp7nI9u4Nj9w",
			"Том 1 Глава 5": "https://yadi.sk/d/pNDxZBowWWvNvA",
			"Том 1 Глава 6": "https://yadi.sk/d/VGpbI29YC6VNJQ",
			"Том 1 Глава 7": "https://yadi.sk/d/66tFAtAb-F8KLg",
			"Том 2 Глава 1": "https://yadi.sk/d/LQanwdDj3WcYKg",
			"Том 2 Глава 10": "https://yadi.sk/d/uYN4YuFvPLYBwQ",
			"Том 2 Глава 11": "https://yadi.sk/d/PT3i52vSsMp61g",
			"Том 2 Глава 12": "https://yadi.sk/d/OOXWLUQdqK6iFQ",
			"Том 2 Глава 13": "https://yadi.sk/d/2rSujDjWBHLGQg",
			"Том 2 Глава 14": "https://yadi.sk/d/5I73kYBqY5wZLQ",
			"Том 2 Глава 15": "https://yadi.sk/d/nBU_xAUWPBYWow",
			"Том 2 Глава 16": "https://yadi.sk/d/oMfoALNmUVxzdw",
			"Том 2 Глава 2": "https://yadi.sk/d/EL5B2tFwI8pb7w",
			"Том 2 Глава 3": "https://yadi.sk/d/egNak36Oj76TZw",
			"Том 2 Глава 4": "https://yadi.sk/d/JYV_A2QqIV4bOA",
			"Том 2 Глава 8": "https://yadi.sk/d/sg-PgK40iGThDQ",
			"Том 2 Глава 9": "https://yadi.sk/d/tGoYiyaG9CN_Rw",
			"Том 3 Глава 1": "https://yadi.sk/d/TMVzIiFE_mOTwg",
			"Том 3 Глава 17": "https://yadi.sk/d/c3YVySRAQa9mRQ",
			"Том 3 Глава 18": "https://yadi.sk/d/oi6frVt9onf1Rg",
			"Том 3 Глава 19": "https://yadi.sk/d/DtuPRRrT97A24Q",
			"Том 3 Глава 20": "https://yadi.sk/d/cttHcY65vfc0iQ",
			"Том 3 Глава 21": "https://yadi.sk/d/7_xwO_ZzLwwp4Q",
			"Том 3 Глава 22": "https://yadi.sk/d/ASfHaUGlPqL8Sg",
			"Том 3 Глава 23": "https://yadi.sk/d/wdUPkPexcVsedA",
			"Том 3 Глава 24": "https://yadi.sk/d/FBiFfzefQkbO6w",
			"Том 3 Глава 25": "https://yadi.sk/d/YzFDubfEEvGCEQ",
			"Том 4 Глава 1": "https://yadi.sk/d/cZyeXiNXYNjsjw",
			"Том 4 Глава 26": "https://yadi.sk/d/koKRMQarQxXbqA",
			"Том 4 Глава 27": "https://yadi.sk/d/y63sGrVan_boEg",
			"Том 4 Глава 28": "https://yadi.sk/d/8dx9RScS2Xe4NQ",
			"Том 4 Глава 29": "https://yadi.sk/d/sgQj9lTUK9y-tw",
			"Том 4 Глава 30": "https://yadi.sk/d/KNTK9r8DVLgoMQ",
			"Том 4 Глава 31": "https://yadi.sk/d/U0duGJpMuQQ0CA",
			"Том 4 Глава 32": "https://yadi.sk/d/sq1JxuFuxLOPlA",
			"Том 4 Глава 33": "https://yadi.sk/d/-XSHanyRZuHBRg",
			"Том 4 Глава 34": "https://yadi.sk/d/4vIapPHuZvjuBw",
			"Том 5 Глава 1": "https://yadi.sk/d/bDjFfVMN2X69FQ",
			"Том 5 Глава 35": "https://yadi.sk/d/wr3GMryrt4I3vA",
			"Том 5 Глава 36": "https://yadi.sk/d/R8XElUqmOQXmGg",
			"Том 5 Глава 37": "https://yadi.sk/d/ZH6RqTNPsTaL2A",
			"Том 5 Глава 38": "https://yadi.sk/d/8uqHmapgzCZyQQ",
			"Том 5 Глава 39": "https://yadi.sk/d/2wmbdHqiUaQxJg",
			"Том 5 Глава 40": "https://yadi.sk/d/Fh7r7Savz1iI1A",
			"Том 5 Глава 41": "https://yadi.sk/d/0ff4XSrQuaCP_g",
			"Том 5 Глава 42": "https://yadi.sk/d/yOYmGdybMZM3iQ",
			"Том 5 Глава 43": "https://yadi.sk/d/31SLcTRcQ5oScQ",
			"Том 6 Глава 1": "https://yadi.sk/d/kGenctzvtrKZUA",
			"Том 6 Глава 44": "https://yadi.sk/d/6DbBEyS2ze7mAQ",
			"Том 6 Глава 45": "https://yadi.sk/d/BUv-KP9ggMy6VQ",
			"Том 6 Глава 46": "https://yadi.sk/d/DwLoT6B6pcWHYQ",
			"Том 6 Глава 47": "https://yadi.sk/d/ZSxowIu9NiFGOg",
			"Том 6 Глава 48": "https://yadi.sk/d/a_-iWrKh2YpinQ",
			"Том 6 Глава 49": "https://yadi.sk/d/GnqpZcIYJeOReg",
			"Том 6 Глава 50": "https://yadi.sk/d/uyl2NdOgW3Gxqw",
			"Том 6 Глава 51": "https://yadi.sk/d/OVZRzHnghRoVSA",
			"Том 6 Глава 52": "https://yadi.sk/d/MNQ8JYzMu5Tsow",
			"Том 7 Глава 53": "https://yadi.sk/d/uMo-Tl-QcFQsTw",
			"Том 7 Глава 54": "https://yadi.sk/d/-E0yN2ALb_RHdQ",
			"Том 7 Глава 55": "https://yadi.sk/d/fJ7N_nXrB8mNUg",
			"Том 7 Глава 56": "https://yadi.sk/d/jQNT_xLobJpiMw",
			"Том 7 Глава 57": "https://yadi.sk/d/AHSAMxoWYAr2EQ",
			"Том 7 Глава 58": "https://yadi.sk/d/jwDxE29xjYlAGg",
			"Том 7 Глава 59": "https://yadi.sk/d/lkMmx_QD-QIA1Q",
			"Том 7 Глава 60": "https://yadi.sk/d/2tyO_-2YMwqA4g",
			"Том 7 Глава 61": "https://yadi.sk/d/tfEnTJm7YnHnkg",
			"Том 8 Глава 1": "https://yadi.sk/d/HMSBRDzou5ZQuQ",
			"Том 8 Глава 62": "https://yadi.sk/d/PXz6w2D97Vxt2g",
			"Том 8 Глава 63": "https://yadi.sk/d/2t4WipJDiH7cBQ",
			"Том 8 Глава 64": "https://yadi.sk/d/6w87y2kf7CxX_Q",
			"Том 8 Глава 65": "https://yadi.sk/d/PNNQX0o7vI4Xog",
			"Том 8 Глава 66": "https://yadi.sk/d/5R0TXDVUFbmtdg",
			"Том 8 Глава 67": "https://yadi.sk/d/EJtAZm_BDWZ4BA",
			"Том 8 Глава 68": "https://yadi.sk/d/YsXdLxl86SlrwA",
			"Том 8 Глава 69": "https://yadi.sk/d/GbJBwb8ew198MA",
			"Том 8 Глава 70": "https://yadi.sk/d/RiLs80PZ0ok4jw",
			"Том 9 Глава 71": "https://yadi.sk/d/bzUbS82P5ZVlVw",
			"Том 9 Глава 72": "https://yadi.sk/d/-2XGPhLQ8ekIJQ",
			"Том 9 Глава 73": "https://yadi.sk/d/zGTPO6pziBEVdg",
			"Том 9 Глава 74": "https://yadi.sk/d/zmtvBYci1Ro2ag",
			"Том 9 Глава 75": "https://yadi.sk/d/8hL5A2RT6LOEEA",
			"Том 9 Глава 76": "https://yadi.sk/d/N8NWu7hM0MawfA",
			"Том 9 Глава 77": "https://yadi.sk/d/hBi9oR8ZXtadqQ",
			"Том 9 Глава 78": "https://yadi.sk/d/QZTjEGUCOJuG7w",
			"Том 9 Глава 79": "https://yadi.sk/d/52VAY7hWMW1uCg",
			"Том 10 Глава 80": "https://yadi.sk/d/MoMNpQbQ8WIV5A",
			"Том 10 Глава 81": "https://yadi.sk/d/YYyM6Bd3Fg7Org",
			"Том 10 Глава 82": "https://yadi.sk/d/8XS4DtS3Kj9dGQ",
			"Том 10 Глава 83": "https://yadi.sk/d/S3Q1QVUl8NIcMg",
			"Том 10 Глава 84": "https://yadi.sk/d/UrNoXj1CWs7YFA",
			"Том 10 Глава 85": "https://yadi.sk/d/euCzzlNdLi9IHQ",
			"Том 10 Глава 86": "https://yadi.sk/d/jRMBPdgn5nKIPA",
			"Том 10 Глава 87": "https://yadi.sk/d/hKd9ep4FM3nujQ",
			"Том 10 Глава 88": "https://yadi.sk/d/J3OQJdL-f8QamA",
			"Том 11 Глава 89": "https://yadi.sk/d/tXUOGpT02LiH4Q",
			"Том 11 Глава 90": "https://yadi.sk/d/DdBm4saLbjzjXw",
			"Том 11 Глава 91": "https://yadi.sk/d/iTcx6AXkvImt2A",
			"Том 11 Глава 92": "https://yadi.sk/d/bl4GDImwL2AgCw",
			"Том 11 Глава 93": "https://yadi.sk/d/ADmu-10FTqUFLQ",
			"Том 11 Глава 94": "https://yadi.sk/d/4MvIeynSEhwYLw",
			"Том 11 Глава 95": "https://yadi.sk/d/39kJN-zS_bQ43w",
			"Том 11 Глава 96": "https://yadi.sk/d/JYGtIwyEP7nhXA",
			"Том 11 Глава 97": "https://yadi.sk/d/0hwASIGNbcmH-A",
			"Том 11 Глава 98": "https://yadi.sk/d/nqWyV7WMeGsEYg",
			"Том 12 Глава 99": "https://yadi.sk/d/3XwuG6EL4DpN-w",
			"Том 12 Глава 100": "https://yadi.sk/d/dUtNoLabKoXt0w",
			"Том 12 Глава 101": "https://yadi.sk/d/0akrof3iFKDW6g",
			"Том 12 Глава 102": "https://yadi.sk/d/FOqKtPzPTU_DEg",
			"Том 12 Глава 103": "https://yadi.sk/d/kW3yCS7LY4_8GQ",
			"Том 12 Глава 104": "https://yadi.sk/d/eIaknaTtazbvMA",
			"Том 12 Глава 105": "https://yadi.sk/d/33_shJpD75bbiw",
			"Том 12 Глава 106": "https://yadi.sk/d/PHNp6Nf30mSM8A",
			"Том 12 Глава 107": "https://yadi.sk/d/JOlgvYPlsphLcQ",
			"Том 12 Глава 108": "https://yadi.sk/d/4FyTv17KvV9oZg",
		},
	},
];
